services:
  web:
    build: .
    container_name: borrowing_app_web
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: borrowings_db
    restart: always
    environment:
      MYSQL_DATABASE: borrowings_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data_hw9:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: borrowing_app_pma
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data_hw9:
